### ISSUE TITLE
DEFECT: tiempo de ejecución es proporcional al número de días

### ISSUE THREAD

**Issue by andresaquino** [petrohs/ydate#1]
Viejo,
hice unos pequeños test y observé que el tiempo de ejecución se incrementa según sea el número de dias, mira:

andresaquino $> time sh ydate.sh -d 20 
20101124

real    0m0.362s
user    0m0.092s
sys     0m0.274s

andresaquino $> time sh ydate.sh -d 200
20100528

real    0m3.398s
user    0m0.886s
sys     0m2.618s

andresaquino $> time sh ydate.sh -d 2000
20050623

real    0m34.517s
user    0m8.870s
sys     0m26.364s

=)

**Comment by petrohs** [comment]
No es un BUG es una FEATURE
Se presenta dado que esta versión realiza un ciclo para ir calculando el día anterior.
Lo registrare en TO-DO para cambiar el algoritmo.

**Comment by andresaquino** [comment]
Listo, encontré el algo para hacerlo más rápido =)
Mis pruebas arrojan lo siguiente:

andresaquino $> getNumberDay "2010" "12" "15"
734426

andresaquino $> time getDayOfNumber $((734426-20))
2010 11 25

real    0m0.001s
user    0m0.000s
sys     0m0.000s

andresaquino $> time getDayOfNumber $((734426-200))
2010 5 29

real    0m0.001s
user    0m0.000s
sys     0m0.000s

andresaquino $> time getDayOfNumber $((734426-2000))
2005 6 24

real    0m0.000s
user    0m0.000s
sys     0m0.000s

andresaquino $> time getDayOfNumber $((734426-20000))
1956 3 13

real    0m0.000s
user    0m0.000s
sys     0m0.000s

vamos a pulirlo y subimos para que lo revises, ujuu !

**Comment by petrohs** [comment]
Va que va
Gracias
